/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Alan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        btnVer = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        itmCerrarSesion = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        itmSalir = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetmainPass (Alpha)");

        btnVer.setText("Ver");
        btnVer.setBounds(450, 170, 110, 90);
        panel.add(btnVer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAgregar.setText("Nuevo");
        btnAgregar.setBounds(173, 170, 110, 90);
        panel.add(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuMenu.setText("Menú");

        itmCerrarSesion.setText("Cerrar sesión");
        menuMenu.add(itmCerrarSesion);
        menuMenu.add(separator);

        itmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itmSalir.setText("Salir");
        menuMenu.add(itmSalir);

        jMenuBar1.add(menuMenu);

        menuUsuarios.setText("Usuarios");
        jMenuBar1.add(menuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnVer;
    public javax.swing.JMenuItem itmCerrarSesion;
    public javax.swing.JMenuItem itmSalir;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu menuMenu;
    public javax.swing.JMenu menuUsuarios;
    public javax.swing.JDesktopPane panel;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables
}
